/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import classifiedDocuments.Measure;
import classifiedDocuments.ResultTesting;
import java.util.List;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingWorker;

/**
 *
 * @author hoan
 */
public class Plan_2 extends javax.swing.JPanel {

    /**
     * Creates new form Plan_2
     */
    
    private String scale;
    public Plan_2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxScale = new javax.swing.JComboBox();
        jLabelState = new javax.swing.JLabel();
        jButtonMeasure = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldSumFileTest = new javax.swing.JTextField();
        jTextFieldSumFileTrain = new javax.swing.JTextField();
        jTextFieldTruePositive = new javax.swing.JTextField();
        jTextFieldFalsePositive = new javax.swing.JTextField();
        jTextFieldAccuracy = new javax.swing.JTextField();

        setBackground(new java.awt.Color(178, 195, 221));
        setPreferredSize(new java.awt.Dimension(678, 440));

        jLabel1.setFont(new java.awt.Font("WenQuanYi Micro Hei", 1, 15)); // NOI18N
        jLabel1.setText("KẾ HOẠCH ĐÁNH GIÁ 2");

        jLabel2.setFont(new java.awt.Font("WenQuanYi Micro Hei", 1, 15)); // NOI18N
        jLabel2.setText("Nội dung");

        jLabel3.setFont(new java.awt.Font("WenQuanYi Micro Hei", 1, 15)); // NOI18N
        jLabel3.setText("Thực hiện");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("\n-Tập D_train và D_test được lấy từ \ntập D theo các tỉ lệ khác nhau\n\n-tỷ lệ: |D_train|=2/3|D|,\n |D_train|=1/3 |D|,\n|D_train|=1/2 |D|\n\n-Yêu cầu người dùng chọn tỷ lệ\n\n-Đánh giá hệ thống theo từng tỷ lệ\nđã chọn \n\n-Kết quả được hiển thị như sau\n\n");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel4.setText("Chọn tỷ lệ |D_train| / |D|");

        jComboBoxScale.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Tỷ lệ", "5/10", "6/10", "7/10", "8/10", "9/10" }));
        jComboBoxScale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxScaleActionPerformed(evt);
            }
        });

        jLabelState.setText("Chưa thực hiện");

        jButtonMeasure.setText("Đánh giá");
        jButtonMeasure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMeasureActionPerformed(evt);
            }
        });

        jLabel6.setText("Số file test");

        jLabel7.setText("Số file train");

        jLabel8.setFont(new java.awt.Font("WenQuanYi Micro Hei", 1, 15)); // NOI18N
        jLabel8.setText("Kết quả đánh giá");

        jLabel9.setText("Số file đúng");

        jLabel10.setText("Số file sai");

        jLabel11.setText("Độ chính xác");

        jTextFieldSumFileTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSumFileTestActionPerformed(evt);
            }
        });

        jTextFieldFalsePositive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFalsePositiveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jComboBoxScale, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelState)
                            .addComponent(jButtonMeasure, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldSumFileTest, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                                    .addComponent(jTextFieldSumFileTrain)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldTruePositive)
                                    .addComponent(jTextFieldFalsePositive)
                                    .addComponent(jTextFieldAccuracy))))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxScale, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jButtonMeasure)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelState)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldSumFileTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldSumFileTrain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextFieldTruePositive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextFieldFalsePositive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTextFieldAccuracy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldSumFileTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSumFileTestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSumFileTestActionPerformed

    private void jTextFieldFalsePositiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFalsePositiveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFalsePositiveActionPerformed

    private void jComboBoxScaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxScaleActionPerformed
        // TODO add your handling code here:
        String value=jComboBoxScale.getSelectedItem().toString();
        if(!value.equals("Tỷ lệ"))
            scale = value;
    }//GEN-LAST:event_jComboBoxScaleActionPerformed

    private void jButtonMeasureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMeasureActionPerformed
        // TODO add your handling code here:
        new Testing().execute();
    }//GEN-LAST:event_jButtonMeasureActionPerformed

    class Testing extends SwingWorker<ResultTesting, Void> {

        @Override
        protected ResultTesting doInBackground() throws Exception {
            ResultTesting resultTesting = new ResultTesting();

            try {
                publish();
                Measure measure = new Measure();
                if(scale!=null){
                    resultTesting = measure.test(5,scale,2);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            return resultTesting;
        }

        @Override
        protected void done() {
            super.done(); //To change body of generated methods, choose Tools | Templates.   
            try {
                ResultTesting resultTesting = get();
                jLabelState.setText("Đã kiểm thử xong!");
                jTextFieldSumFileTest.setText(String.valueOf(resultTesting.getSumFileTest()));
                jTextFieldSumFileTrain.setText(String.valueOf(resultTesting.getSumFileTrain()));
                jTextFieldFalsePositive.setText(String.valueOf(resultTesting.getSumFalesPos()));
                jTextFieldTruePositive.setText(String.valueOf(resultTesting.getSumTruePos()));
                jTextFieldAccuracy.setText(String.valueOf(resultTesting.getAccuracy()));
                

            } catch (InterruptedException ex) {
                Logger.getLogger(Plan_2.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ExecutionException ex) {
                Logger.getLogger(Plan_2.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

        @Override
        protected void process(List<Void> chunks) {
            //To change body of generated methods, choose Tools | Templates.
            jLabelState.setText("Đang kiểm thử...");
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMeasure;
    private javax.swing.JComboBox jComboBoxScale;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelState;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldAccuracy;
    private javax.swing.JTextField jTextFieldFalsePositive;
    private javax.swing.JTextField jTextFieldSumFileTest;
    private javax.swing.JTextField jTextFieldSumFileTrain;
    private javax.swing.JTextField jTextFieldTruePositive;
    // End of variables declaration//GEN-END:variables
}
