/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import classifiedDocuments.Measure;
import classifiedDocuments.ResultTesting;
import java.util.List;
import java.util.concurrent.ExecutionException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SwingWorker;

/**
 *
 * @author hoan
 */
public class Plan_1 extends javax.swing.JPanel {

    /**
     * Creates new form Plan_1
     */
    private String posFileTest;
    public Plan_1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jComboBoxPos = new javax.swing.JComboBox();
        jButtonMeasure = new javax.swing.JButton();
        jLabelState = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldSumFileTest = new javax.swing.JTextField();
        jTextFieldSumFileTrain = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldTruePositive = new javax.swing.JTextField();
        jTextFieldFalsePositive = new javax.swing.JTextField();
        jTextFieldAccuracy = new javax.swing.JTextField();

        setBackground(new java.awt.Color(178, 195, 221));
        setPreferredSize(new java.awt.Dimension(678, 440));

        jLabel1.setFont(new java.awt.Font("WenQuanYi Micro Hei", 1, 15)); // NOI18N
        jLabel1.setText("KẾ HOẠCH ĐÁNH GIÁ 1");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("\n-Chia tập D ra thành 5 phần xấp xỉ \nbằng nhau\n\n-Yêu cầu người dùng chọn \nphần nào để làm D_test\n\n-Tiền hành kiểm thử  5 lần,\n mỗi lần ta lấy một phần làm \nD_test, 4 phần còn lại làm D_train\n\n-Kết quả thu được sẽ được\n hiển thị như dưới đây\n\n");
        jScrollPane1.setViewportView(jTextArea1);

        jLabel2.setFont(new java.awt.Font("WenQuanYi Micro Hei", 1, 15)); // NOI18N
        jLabel2.setText("Nội dung");

        jLabel3.setFont(new java.awt.Font("WenQuanYi Micro Hei", 1, 15)); // NOI18N
        jLabel3.setText("Thực hiện");

        jLabel4.setText("Chọn ví trí phần làm D_test");

        jComboBoxPos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Vị trí", "phần 1", "phần 2", "phần 3", "phần 4", "phần 5", "phần 6", "phần 7", "phần 8", "phần 9", "phần 10" }));
        jComboBoxPos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPosActionPerformed(evt);
            }
        });

        jButtonMeasure.setText("Đánh giá");
        jButtonMeasure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMeasureActionPerformed(evt);
            }
        });

        jLabelState.setText("Chưa thực hiện");

        jLabel6.setText("Số file D_test");

        jLabel7.setText("Số file D_train");

        jLabel8.setFont(new java.awt.Font("WenQuanYi Micro Hei", 1, 15)); // NOI18N
        jLabel8.setText("Kết quả đánh giá");

        jLabel9.setText("Số file đúng");

        jLabel10.setText("Số file sai");

        jLabel11.setText("Độ chính xác");

        jTextFieldTruePositive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTruePositiveActionPerformed(evt);
            }
        });

        jTextFieldFalsePositive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldFalsePositiveActionPerformed(evt);
            }
        });

        jTextFieldAccuracy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAccuracyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldAccuracy))
                            .addComponent(jButtonMeasure, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(jLabelState)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldSumFileTest, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(8, 8, 8)
                                .addComponent(jTextFieldSumFileTrain))
                            .addComponent(jComboBoxPos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldTruePositive)
                                    .addComponent(jTextFieldFalsePositive))))))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxPos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonMeasure)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelState)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextFieldSumFileTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextFieldSumFileTrain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextFieldTruePositive, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldFalsePositive)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldAccuracy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 79, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxPosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPosActionPerformed
        // TODO add your handling code here:
        String cb = jComboBoxPos.getSelectedItem().toString();
        if(!cb.equals("Vị trí"))
            posFileTest = cb;
    }//GEN-LAST:event_jComboBoxPosActionPerformed

    private void jTextFieldTruePositiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTruePositiveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTruePositiveActionPerformed

    private void jTextFieldFalsePositiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldFalsePositiveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldFalsePositiveActionPerformed

    private void jTextFieldAccuracyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAccuracyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAccuracyActionPerformed

    private void jButtonMeasureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMeasureActionPerformed
        // TODO add your handling code here:
        
          new Testing().execute();
    }//GEN-LAST:event_jButtonMeasureActionPerformed
 class Testing extends SwingWorker<ResultTesting, Void> {

        @Override
        protected ResultTesting doInBackground() throws Exception {
            ResultTesting resultTesting = new ResultTesting();

            try {
                publish();
                Measure measure = new Measure();
                if(posFileTest!=null){
                    resultTesting = measure.test(10,posFileTest,1);
                }else{
                    JOptionPane.showMessageDialog(null," Bạn phải chọn vị trí file test");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            return resultTesting;
        }

        @Override
        protected void done() {
            super.done(); //To change body of generated methods, choose Tools | Templates.   
            try {
                ResultTesting resultTesting = get();
                jLabelState.setText("Đã kiểm thử xong!");
                jTextFieldSumFileTest.setText(String.valueOf(resultTesting.getSumFileTest()));
                jTextFieldSumFileTrain.setText(String.valueOf(resultTesting.getSumFileTrain()));
                jTextFieldFalsePositive.setText(String.valueOf(resultTesting.getSumFalesPos()));
                jTextFieldTruePositive.setText(String.valueOf(resultTesting.getSumTruePos()));
                jTextFieldAccuracy.setText(String.valueOf(resultTesting.getAccuracy()));
                

            } catch (InterruptedException ex) {
                Logger.getLogger(Plan_1.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ExecutionException ex) {
                Logger.getLogger(Plan_1.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

        @Override
        protected void process(List<Void> chunks) {
//To change body of generated methods, choose Tools | Templates.
            jLabelState.setText("Đang kiểm thử...");
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMeasure;
    private javax.swing.JComboBox jComboBoxPos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelState;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextFieldAccuracy;
    private javax.swing.JTextField jTextFieldFalsePositive;
    private javax.swing.JTextField jTextFieldSumFileTest;
    private javax.swing.JTextField jTextFieldSumFileTrain;
    private javax.swing.JTextField jTextFieldTruePositive;
    // End of variables declaration//GEN-END:variables
}
